version: 2
jobs:
  build:
    working_directory: ~/eslint-config-connehito
    docker:
      - image: node:8.11
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/eslint-config-connehito/node_modules
            - ~/.cache/yarn/
